<head>
<link rel="stylesheet" type="text/css" href="css/stylesheet.css">
</head>
	
	<body>

<!-- ><h3>Introduction</h3> -->

<div id="headerBanner">
	
	<img src="imgs/logo.png"/>
	
</div>

<div id="imageBanner">
	<div class="imageBannerCell"><img minimal-lightbox class="header" src="imgs/orbitRender.gif"/></div>
	<div class="imageBannerCell"><img minimal-lightbox style=" margin-top: -2em;" class="header" src="imgs/IMG_6505.jpg"/></div>
	<div class="imageBannerCell"><img minimal-lightbox class="header" src="imgs/frontView.png"/></div>
</div>

<div id="page">
	<h1>Leap Motion Reference AR Headset - Project North Star (Rev 1)</h1>
	
<hr/>


<div id="introWrapper">
<h3>Introduction</h3>

The purpose of this guide is to instruct, with access to a few common tools, how to make a North Star reference AR headset. It's aimed to be accessible and inexpensive to build, using as many off-the-shelf components and 3D-printed parts as possible. At the same time, several key components are custom-made (e.g. the reflectors, display driver board, and Leap Motion hand tracking module.)<br/><br/> 

Although not a complete AR solution, Project North Star points to a future where the physical and virtual worlds blend together into a single magical experience. With it we hope to gather like-minded people and build that future together.<br/><br/>

<a id="CADfiles" href="./North%20Star%203D%20Files/">Download 3D CAD files</a> 
</div>

<div style="width:33%;margin-left:15%;display:inline-block">
<h3>Table of Contents</h3>
<ol>
	<li>Introduction</li>
	<li>Tools & Materials</li>
	<li>BOM</li>
	<li>3D Printed Parts</li>
	<!-- <li>Sanding and Finishing</li> -->
	<li>Assembly Instructions</li>
	<li>Calibration</li>
	<li>Notes</li>
	
</ol>
</div><br/><br/>


<hr/>
<h3>Tools & Materials</h3>
<ul id="">
	<li>3D printer and software: <a href="https://www.makergear.com/products/m2">MakerGear M2</a>, <a href="https://www.simplify3d.com/">Simplify3D</a>, print profiles: <a href="https://www.thingiverse.com/thing:269637"> Rsilver's M2 Simplify 3D optimized profiles, Thingiverse</a></li>
	<li>Filament: <a href="https://www.amazon.com/eSUN-1-75mm-Printer-Filament-2-2lbs/dp/B01EKEMB7Q">eSun PLA+, Amazon</a></li>
	<li>T6 Torx driver for thin-plastic screws</li>
	<li>Phillips driver for M2.5 screws</li>
	<li>M2.5 Screw thread tap *: <a href="https://www.mcmaster.com/#26475a33">M2.5 x 0.45 mm Thread Tap, McMaster</a><br/>
	<!-- ><span>* Alternatively can use <a href="https://www.mcmaster.com/#93625a102">matching nuts</a> instead of tapping material</span> -->
	<li>Hot glue gun (on low setting ~ 40W)</li>
	<li>Latex gloves (minimize fingerprints on optical components)</li>
	<li>Optional: 3D print finishing tools (wire cutters, small chisel, file, sand paper, etc.)</li>
</ul>
<hr/>
<img minimal-lightbox style="float:right;width:400px;" src="imgs/BOMReference.png"/>

<h3>BOM</h3>

<ol id="BOM">

<li>Leap Motion next-generation ultra-wide tracking module<br/><br/>
 Coming soon!
</li>
<hr/>
<li>Leap Motion display driver <br/><br/>
Coming soon!
</li>
<hr/>
<li>BOE 3.5-inch 120Hz LCDs<br/>
	VS035ZSM-NW0 - 3.5inch LTPS 1440*1600 Module<br/><br/>
	
	<img minimal-lightbox src="imgs/IMG_0701.JPG"/><br/><br/>
</li>
<hr/>
<li>
Reflectors (aka combiners, lenses)<br/><br/>

What may seem intimidating at first is conceptually very simple. One property of elipsoids is that all the light emitted from one focus reflects off its surface and focuses it to the second focus! Amazing. Therefore, to figure out the section of elipsoid needed in our AR application, we traced a ray backwards from the second focus, through a cellphone-sized display. <br/><br/> 

The resultant elipsoid is defined by the following dimensions, chosen to allow a range of 3-to-5-inch LCD panels to be placed near the eye. The perimeter of the elipsoid section was decided on empirically by minimizing distortion with a larger prototype, then cropping to the reflected image. This large reflector was roughly 120x120mm, and the final ended up being around 75x75mm.<br/>
<img minimal-lightbox src="imgs/ElipsoidReflector.png"/><img minimal-lightbox src="imgs/reflectorDimensions.png"/><br/><br/>

The reflectors are diamond-turned and milled from PMMA (a.k.a. acrylic). The outside surface needs an anti-reflective coating to prevent a secondary reflection from degrading the image. Indoors and subjectively, 50-50% (transmissive-reflective) anti-reflective coating provided the best results for us.<br/>
<img minimal-lightbox src="imgs/reflectorOverview.png"/><br/><br/>

From the elipsoid definition, the reflectors need to be rotated and translated into position. We define the origin point as the midpoint between the two reflector foci, which should line up with the user's pupils:<br/><br/>

<img minimal-lightbox src="imgs/OpticsTransformations.png"/>

<img src="imgs/ReflectorEnd.png"/><img minimal-lightbox src="imgs/ReflectorsFront.png"/><br/><br/>


</li>
<hr/>
<li>

OEM Welder's Mask Headgear replacement<br/><br/>

Light and adjustable with rigid mount points. Several welder's mask headgear vendors were tested, but most failed to be rigid or comfortable for our applications. Their general design is made of injection-molded plastic features that tighten onto either side of a welding faceshield. Although it may be desireable for those features to be flexible and compliant while welding, our heavier AR assemblies caused the headgear to flex and/or dig into the users' head. (Ouch.) The following Miller branded model's had the least flex and provided the a rigid "clamping" to the head. It really helps to be lightweight as well.<br/><br/>

These two specific generations of headgears yielded the best results, mounting evolving electronics on the most varied heads. The amount of adjustment points makes it work for the large majority of users.<br/><br/>
	
Welding Replacement Headgear - <a href="https://www.amazon.com/Miller-Headgear-Generation-Welding-Helmets/dp/B073QY6B7Y">Miller Generation IV for T94 Headgear, Amazon</a> Part #260486 or <a href="https://www.amazon.com/Miller-Electric-256174-Headgear-Helmet/dp/B00826AM7A" >Miller Replacement Headgear, Amazon </a> Part #256174
<br/></br>
	<img minimal-lightbox src="imgs/millereplacement.jpg"/><img minimal-lightbox src="imgs/millergen4.jpg"/><img minimal-lightbox src="imgs/headgearExample.png"/><br>
</li>
<hr/>
<li>
[Qty: 6] Delta PT screws M2.0 x 6 mm Long "Thread-Forming Screws for Thin Plastic" - <a href="https://www.mcmaster.com/#96817a209"> McMaster #96817a209</a> <br/></br>
	<img minimal-lightbox src="imgs/96817a209l.gif"/></br>
</li>
<hr/>
<li>	
[Qty:12] M2.5 x 0.45 mm Thread, 6 mm Long "Steel Pan Head Phillips Screw" - <a href="https://www.mcmaster.com/#92005a066"> McMaster #92005a066</a><br/></br>
	<img minimal-lightbox src="imgs/92005a066l.gif"/><br>
</li>
<hr/>

<li> [Qty:2 pairs] Hinge rotation fasteners</br></br>
	Machine screws, 10-32 Thread Size, 7/8" Long "Steel Button Head Hex Drive Screw" - <a href="https://www.mcmaster.com/#92949a270"> McMaster #92949a270</a><br/>
	Matching nuts, 10-32 Thread Size, Stainless "Steel Nylon-Insert Locknut" - <a href="https://www.mcmaster.com/#91831a411">McMaster #91831a411</a><br/>
	<img minimal-lightbox src="imgs/92949a270l.gif">
	<img minimal-lightbox src="imgs/91831a411l.gif">
	
</li>

<hr/>
<li>
[Qty:2] 3x10mm Al. bar stock cut to approximately 150mm length
<a href="https://www.mcmaster.com/#9146t21"> McMaster #92005a066</a><br/></br>
	<img minimal-lightbox src="imgs/9146T213p1.png"/><br>
	Cut, drill, and tap the slides to roughly 150mm (6 inches) in length. We used a Dremel rotary tool to cut the bar stock to length, and transferred the hole pattern from the Halo 3D print using a <a href="https://www.amazon.com/gp/product/B008DXYOLC/ref=oh_aui_search_detailpage?ie=UTF8&psc=1">transfer punch.</a> The two holes are tapped using <a href="https://www.mcmaster.com/#26475a33">M2.5 x 0.45 mm Thread Tap, McMaster</a><br/>
	<br/><br/>
	
	Cost and speed being the most important design parameters, this DIY method performs as well as a machined part at 100x lower price. Without access to a CNC metal workshop it's surprisingly expensive to have 1-2 parts machined.<br/><br/>

	<img minimal-lightbox src="imgs/IMG_5222.JPG"/>
	<img minimal-lightbox src="imgs/IMG_4481.JPG"/>
	<img minimal-lightbox src="imgs/slideDimensions.png"/>
	<br/><br/>

	
</li>
<hr/>
<li>
	3D Printed Parts
</li>
</ol>

Note: Use your slicer's part orientation tools to ensure flat contact with print surface. In Simplify 3D, it can be found in the menu "Edit > Place Surface On Bed"

<ol>
<li><h5>Optics Bracket</h5>
	
	The optics bracket is the most difficult part to FDM print. The toed-in optics and long thin beams require a tuned printer and large print bed (200x250mm). To reduce the chance for print failure, support material is manually removed where it is thin and tall (see image below). Furthermore, to alleviate the finishing work, the print is separated into 2 print profiles: fast and high-res. The high-res profile's goal is to reduce stepping on the near-horizontal crossbeam. Afterwards, a file and 220-grit sandpaper very quickly make the surface passable without the need for filler. Although printing the entire bracket with one profile also produces good brackets, this hybrid solution saved time and produced better results without much effort. Makes sense if a file and sand paper is already available.<br/><br/>

	All the optical components are mounted to this bracket. Take your time, be meticulous. It's crucial that care is taken in producing a good print. This will save time during calibration.
	<br/>


	<img minimal-lightbox src="imgs/bedPlacement_opticsBracket.png"/>
	<video src="imgs/timelapses/opticsBrackWHITEBigTabs_20180425052347.mp4" controls></video>
	<img minimal-lightbox src="imgs/bedPlacement_OpticsSupports.png"/><br/>

	<img minimal-lightbox src="imgs/IMG_6551.jpg"/>
	<img minimal-lightbox src="imgs/IMG_9233.jpg"/><br/>

	<table>
		<tr><td colspan=2>Print from: 0 - 5mm:</td></tr>
		<tr><td>layer height</td><td>0.25mm</td></tr>
		<tr><td>infill</td><td>20% rectilinear</td></tr>
		<tr><td>top/bottom layers</td><td>3</td></tr>
		<tr><td>perimeter walls</td><td>2</td></tr>
		<tr><td>temperature</td><td>200 C</td></tr>
		<tr><td>supports</td><td>yes, 60% infill</td></tr>
	</table>
	<table>
		<tr><td colspan=2>Print from: 5 - 32mm:</td></tr>
		<tr><td>layer height</td><td>0.15mm</td></tr>
		<tr><td>infill</td><td>20% rectilinear</td></tr>
		<tr><td>top/bottom layers</td><td>6</td></tr>
		<tr><td>perimeter walls</td><td>3</td></tr>
		<tr><td>temperature</td><td>200 C</td></tr>
		<tr><td>supports</td><td>yes, 40% infill</td></tr>
	
	</table>
	<table>
		<tr><td colspan=2>Print from: 32mm - end:</td></tr>
		<tr><td>layer height</td><td>0.25mm</td></tr>
		<tr><td>infill</td><td>20% rectilinear</td></tr>
		<tr><td>top/bottom layers</td><td>3</td></tr>
		<tr><td>perimeter walls</td><td>2</td></tr>
		<tr><td>temperature</td><td>200 C</td></tr>
		<tr><td>supports</td><td>yes, 60%</td></tr>
	
	</table><br/><br/>

</li>	
<hr class="print"/>
<li><h5>Halo</h5>
	<img minimal-lightbox src="imgs/bedPlacement_halo.png"/>
	<img minimal-lightbox src="imgs/IMG_6514.JPG"/>
	<video src="imgs/timelapses/HaloOptimized_20180426171820.mp4" controls></video>
	<br/>
	<table>
		<tr><td>layer height</td><td>0.25mm</td></tr>
		<tr><td>infill</td><td>20% rectilinear</td></tr>
		<tr><td>top/bottom layers</td><td>3</td></tr>
		<tr><td>perimeter walls</td><td>2</td></tr>
		<tr><td>temperature</td><td>200 C</td></tr>
		<tr><td>supports</td><td>yes</td></tr>
	</table>

</li>

<hr class="print"/>	
<li><h5>Lid</h5>
	<img minimal-lightbox src="imgs/bedPlacement_haloLid.png"/>
	<img minimal-lightbox src="imgs/IMG_8902.JPG" />
	<video src="imgs/timelapses/LatestLid_20180423202548.mp4" controls></video>
	<br/>
	<table>
		<tr><td>layer height</td><td>0.25mm</td></tr>
		<tr><td>infill</td><td>20% rectilinear</td></tr>
		<tr><td>top/bottom layers</td><td>3</td></tr>
		<tr><td>perimeter walls</td><td>2</td></tr>
		<tr><td>temperature</td><td>200 C</td></tr>
		<tr><td>supports</td><td>no</td></tr>
	</table>

</li>
<hr class="print"/>
<li><h5>Electronics Tray</h5>
	<img minimal-lightbox src="imgs/bedPlacement_electronicsTray.png"/>
	<img minimal-lightbox src="imgs/IMG_5822.JPG"/>
	<video src="imgs/timelapses/ARElectronicsTray_20180425012536.mp4" controls></video>
	<br/>
	<table>
		<tr><td>layer height</td><td>0.25mm</td></tr>
		<tr><td>infill</td><td>20% rectilinear</td></tr>
		<tr><td>top/bottom layers</td><td>3</td></tr>
		<tr><td>perimeter walls</td><td>2</td></tr>
		<tr><td>temperature</td><td>200 C</td></tr>
		<tr><td>supports</td><td>no</td></tr>
	</table>



</li>	
<hr class="print"/>
<li><h5>USB Strain relief</h5>
	<img minimal-lightbox src="imgs/bedPlacement_strainRelief.png"/>

	<img minimal-lightbox src="imgs/IMG_9208.JPG"/>
	<video src="imgs/timelapses/USBStrainRelief-CamSafe_20180425010142.mp4" controls></video>
	<br/>
	<table>
		<tr><td>layer height</td><td>0.25mm</td></tr>
		<tr><td>infill</td><td>20% rectilinear</td></tr>
		<tr><td>top/bottom layers</td><td>3</td></tr>
		<tr><td>perimeter walls</td><td>2</td></tr>
		<tr><td>temperature</td><td>200 C</td></tr>
		<tr><td>supports</td><td>no</td></tr>
	</table>
</li>
<hr class="print"/>	
<li><h5>Display Tray</h5>
<img minimal-lightbox src="imgs/bedPlacement_displayTray.png"/>
<video src="imgs/timelapses/DisplayTrayLatestLowTempOptimizedMirrored_20180425183308.mp4" controls></video>

<br/><br/>

The print is done using multiple print profiles to minimize the need for support material. By printing the feature at a lower temperature the plastic can span longer distances without support. Also, align the print roughly as shown (~45 degrees) to prevent the support material from printing orthogonal to lip.<br/><br/>

After printing, remove and clean up any support material so that the display slides in easily. We used a sharp chisel to scrap away any remaining plastic burs.<br/><br/>

Check the lip of the part is flat and consistent throughout to prevent any extra light leaking from the edges of the LCD panels.<br/><br/>

Optional step is tapping the screw holes to make sure any extra plastic is removed and the screws will fasten smoothly.
<br/>

<img minimal-lightbox src="imgs/IMG_2692.JPG"/><img minimal-lightbox src="imgs/IMG_5909.JPG"/><img minimal-lightbox src="imgs/IMG_1365.JPG"/>

<br/>
<table>
	<tr><td colspan=2>Print from: 0 - 3mm:</td></tr>
	<tr><td>layer height</td><td>0.25mm</td></tr>
	<tr><td>infill</td><td>20% rectilinear</td></tr>
	<tr><td>top/bottom layers</td><td>3</td></tr>
	<tr><td>perimeter walls</td><td>2</td></tr>
	<tr><td>temperature</td><td>200 C</td></tr>
	<tr><td>supports</td><td>yes</td></tr>
	
</table>

<table>
	<tr><td colspan=2>Print from: 3mm - end:</td></tr>
	<tr><td>layer height</td><td>0.25mm</td></tr>
	<tr><td>infill</td><td>20% rectilinear</td></tr>
	<tr><td>top/bottom layers</td><td>3</td></tr>
	<tr><td>perimeter walls</td><td>2</td></tr>
	<tr><td>temperature</td><td>190 C</td></tr>
	<tr><td>supports</td><td>yes</td></tr>
	
</table>

</li>	
<hr class="print"/>
<li><h5>Hinges (left and right pairs)</h5>
	<img minimal-lightbox src="imgs/bedPlacement_hingeA.png"/><img minimal-lightbox src="imgs/bedPlacement_hingeB.png"/>
	<img minimal-lightbox src="imgs/IMG_1130.JPG"/>
	<video src="imgs/timelapses/hingesPair_20180425213458.mp4" controls></video>

	<video src="imgs/timelapses/hingesPairTracks_20180425230035.mp4" controls></video>
<br/>
	<table>
		<tr><td>layer height</td><td>0.25mm</td></tr>
		<tr><td>infill</td><td>20% rectilinear</td></tr>
		<tr><td>top/bottom layers</td><td>3</td></tr>
		<tr><td>perimeter walls</td><td>2</td></tr>
		<tr><td>temperature</td><td>200 C</td></tr>
		<tr><td>supports</td><td>yes</td></tr>
	</table>

</li>
<hr class="print"/>
<li><h5>Slide endcaps</h5>

<img minimal-lightbox src="imgs/bedPlacement_endCaps.png"/>

<img minimal-lightbox src="imgs/IMG_5852.JPG"/>
<video src="imgs/timelapses/endCaps_20180425203542 2.mp4" controls></video>
<br/>
<table>
	<tr><td>layer height</td><td>0.25mm</td></tr>
	<tr><td>infill</td><td>20% rectilinear</td></tr>
	<tr><td>top/bottom layers</td><td>3</td></tr>
	<tr><td>perimeter walls</td><td>2</td></tr>
	<tr><td>temperature</td><td>200 C</td></tr>
	<tr><td>supports</td><td>yes</td></tr>
</table>

</li>	
</ol>

<hr/>
<h3>Assembly Steps</h3>
<p>The NorthStar headset has three main sub-assemblies: the optics bracket, the electronics tray, and the adjustable headgear.</p>

<strong>Adjustable headgear:</strong><br/><br/>
1) Verify the aluminum bar stock slides without resistance inside the 3D printed hinges. Tip: Repeatedly sliding the bar stock quickly through a new hinge clears out any obtrusive burs, and the heat generated shapes the plastic.<br/>
2) Disassemble old hinges from headgear, set aside the o-rings:<br/>
<img minimal-lightbox src="imgs/IMG_6541.JPG" />
<img minimal-lightbox src="imgs/IMG_6539.JPG" /><br/><br/>


3) Assemble new hinge as shown below, using screw/nut <span class="BOMRef">H</span>. Tighten until the o-ring is still visible and the hinge has considerable resistance turning.<br/>
4) Slide hinge onto headgear, aligning with front of track. Lock in place using screw <span class="BOMRef">F</span><br/>
<img minimal-lightbox src="imgs/IMG_6542.JPG" />
<img minimal-lightbox src="imgs/IMG_6550.JPG" /><br/><br/>


<strong>Electronics Tray:</strong><br/><br/>

5) Fasten display driver <span class="BOMRef">B</span> to 3D printed bracket using <span class="BOMRef">F</span> screws x 3. Fasten hand tracking module <span class="BOMRef">A</span> to 3D print using screws from its enclosure<br/>
<img minimal-lightbox src="imgs/IMG_5446.JPG" />
<img minimal-lightbox src="imgs/IMG_5873.JPG" /><br/><br/>

6) Place USB cable into USB strain relief, and fasten using <span class="BOMRef">F</span> screws x 2 to electronics tray<br/>
7) Adjust USB cable until the flex connector is aligned with connector and doesn't strain <br/>
<img minimal-lightbox src="imgs/IMG_7105.JPG" />

<img minimal-lightbox src="imgs/IMG_8951.JPG" /><br/><br/>

Optics Bracket:<br/><br/>

8) Fasten electronics tray to halo using 2 screws <span class="BOMRef">F</span><br/>
9) Fasten optics bracket to the halo using 6 screws <span class="BOMRef">F</span><br/>
<img src="imgs/IMG_1653.JPG"/><br/><br/>

10) Fasten displays and facial interfaces into optics bracket using 4 screws per side <span class="BOMRef">G</span> (8 total). <br/>
11) Carefully connect the display flex connector to the driver board <br/>
<img src="imgs/IMG_6573.jpg"/><img src="imgs/IMG_8165.JPG"/><img src="IMG_1849.JPG"/><br/><br/>

12) Fasten lid to halo using 4 screws <span class="BOMRef">F</span> from the bottom as shown<br/>
13) Secure wires to lid using cable-ties through the anchors<br/>
<img src="imgs/IMG_1849.JPG"/><img src="imgs/IMG_1981.JPG"/><br/><br/>

14) Verify reflectors align with tabs in optics bracket, scrape away offending plastic if not. Using hot-glue, "tack" the reflectors into the halo bracket. Be careful not to use too much and be quick enough that the glue doesn't solidify before the reflectors are in place.<br/><br/>
<img src="imgs/IMG_6585.jpg"/><br/><br/>
Final Assembly:<br/><br/>

15) Fasten slides to assembled optics bracket using 4 x <span class="BOMRef">G</span> screws <br/>

<img src="imgs/IMG_7997.JPG"/><br/><br/>

16) Make adjustments for user's head.
<hr/>
<h3>Calibration</h3>
<hr/>
<h3>Notes</h3>
<ul>
<li>not optimal for users with glasses</li>
<li>electronics bracket hard to access/service once installed</li>
<li>no wire management for display flex connectors</li>
<li>imbalanced weight due to cables: USB, display port, and power</li>
</ul>

</div>
<script src="js/minimal.lightbox.js" type="text/javascript" charset="utf-8"></script>
<script src="js/jquery.min.js"></script>
</body>
