Started logging messages at Sat Jan 30 13:38:48 2021
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: On
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 79 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 85
Info:            Created 
Info:        Working on 86
Info:            Created 
Info:        Working on 130
Info:            Created 
Info:        Working on 134
Info:            Created 
Info:        Working on 8
Info:            Created 
Info:        Working on 121
Info:            Created 
Info:        Working on 122
Info:            Created 
Info:        Working on 188
Info:            Created 
Info:        Working on 195
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 189
Info:            Created 
Info:        Working on 321
Info:            Created 
Info:        Working on 17
Info:            Created 
Info:        Working on 317
Info:            Created 
Info:        Working on 318
Info:            Created 
Info:        Working on 495
Info:            Created 
Info:        Working on 747
Info:            Created 
Info:        Working on 758
Info:            Created 
Info:        Working on 506
Info:            Created 
Info:        Working on 26
Info:            Created 
Info:        Working on 484
Info:            Created 
Info:        Working on 485
Info:            Created 
Info:        Working on 728
Info:            Created 
Info:        Working on 1012
Info:            Created 
Info:        Working on 1023
Info:            Created 
Info:        Working on 733
Info:            Created 
Info:        Working on 47
Info:            Created 
Info:        Working on 716
Info:            Created 
Info:        Working on 1002
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 996
Info:            Created 
Info:        Working on 970
Info:            Created 
Info:        Working on 670
Info:            Created 
Info:        Working on 446
Info:            Created 
Info:        Working on 159
Info:            Created 
Info:        Working on 1274
Info:            Created 
Info:        Working on 1275
Info:            Created 
Info:        Working on 1188
Info:            Created 
Info:        Working on 907
Info:            Created 
Info:        Working on 275
Info:            Created 
Info:        Working on 1503
Info:            Created 
Info:        Working on 1504
Info:            Created 
Info:        Working on 1611
Info:            Created 
Info:        Working on 1507
Info:            Created 
Info:        Working on 454
Info:            Created 
Info:        Working on 600
Info:            Created 
Info:        Working on 601
Info:            Created 
Info:        Working on 858
Info:            Created 
Info:        Working on 1136
Info:            Created 
Info:        Working on 1187
Info:            Created 
Info:        Working on 900
Info:            Created 
Info:        Working on 386
Info:            Created 
Info:        Working on 380
Info:            Created 
Info:        Working on 895
Info:            Created 
Info:        Working on 1184
Info:            Created 
Info:        Working on 1434
Info:            Created 
Info:        Working on 1571
Info:            Created 
Info:        Working on 1363
Info:            Created 
Info:        Working on 1105
Info:            Created 
Info:        Working on 825
Info:            Created 
Info:        Working on 562
Info:            Created 
Info:        Working on 345
Info:            Created 
Info:        Working on 554
Info:            Created 
Info:        Working on 813
Info:            Created 
Info:        Working on 1244
Info:            Created 
Info:        Working on 1646
Info:            Created 
Info:        Working on 1674
Info:            Created 
Info:        Working on 1655
Info:            Created 
Info:        Working on 1713
Info:            Created 
Info:        Working on 1602
Info:            Created 
Info:        Working on 1410
Info:            Created 
Info:        Working on 1156
Info:            Created 
Info:        Working on 872
Info:            Created 
Info:        Working on 844
Info:            Created 
Info:        Working on 845
Info:            Created 
Info:        Working on 1124
Info:            Created 
Info:        Working on 1125
Info:            Created 
Info:        Working on 1378
Info:            Created 
Info:        Working on 1379
Info:            Created 
Info:        Working on 1579
Info:            Created 
Info:        Working on 1580
Info:            Created 
Info:        Working on 1459
Info:            Created 
Info:        Working on 1774
Info:            Created 
Info:        Working on 1223
Info:            Created 
Info:        Working on 1828
Info:            Created 
Info:        Working on 1807
Info:            Created 
Info:        Working on 1827
Info:            Created 
Info:        Working on 1733
Info:            Created 
Info:        Working on 1635
Info:            Created 
Info:        Working on 213
Info:            Created 
Info:        Working on 445
Info:            Created 
Info:        Working on 947
Info:            Created 
Info:        Working on 1093
Info:            Created 
Info:        Working on 540
Info:            Created 
Info:        Working on 535
Info:            Created 
Info:        Working on 804
Info:            Created 
Info:        Working on 1087
Info:            Created 
Info:        Working on 1353
Info:            Created 
Info:        Working on 1196
Info:            Created 
Info:        Working on 920
Info:            Created 
Info:        Working on 644
Info:            Created 
Info:        Working on 412
Info:            Created 
Info:        Working on 250
Info:            Created 
Info:        Working on 241
Info:            Created 
Info:        Working on 401
Info:            Created 
Info:        Working on 630
Info:            Created 
Info:        Working on 1422
Info:            Created 
Info:        Working on 1607
Info:            Created 
Info:        Working on 1699
Info:            Created 
Info:        Working on 1640
Info:            Created 
Info:        Working on 1470
Info:            Created 
Info:        Working on 1232
Info:            Created 
Info:        Working on 959
Info:            Created 
Info:        Working on 680
Info:            Created 
Info:        Working on 660
Info:            Created 
Info:        Working on 938
Info:            Created 
Info:        Working on 1214
Info:            Created 
Info:        Working on 1450
Info:            Created 
Info:        Working on 1625
Info:            Created 
Info:        Working on 1728
Info:            Created 
Info:        Working on 1789
Info:            Created 
Info:        Working on 1826
Info:            Created 
Info:        Working on 1590
Info:            Created 
Info:        Working on 1389
Info:            Created 
Info:        Working on 1711
Info:            Created 
Info:        Working on 1777
Info:            Created 
Info:        Working on 155
Info:            Created 
Info:        Working on 1262
Info:            Created 
Info:        Working on 1263
Info:            Created 
Info:        Working on 1328
Info:            Created 
Info:        Working on 1051
Info:            Created 
Info:        Working on 1473
Info:            Created 
Info:        Working on 271
Info:            Created 
Info:        Working on 1169
Info:            Created 
Info:        Working on 1425
Info:            Created 
Info:        Working on 1520
Info:            Created 
Info:        Working on 450
Info:            Created 
Info:        Working on 1514
Info:            Created 
Info:        Working on 1658
Info:            Created 
Info:        Working on 1596
Info:            Created 
Info:        Working on 1399
Info:            Created 
Info:        Working on 1172
Info:            Created 
Info:        Working on 694
Info:            Created 
Info:        Working on 526
Info:            Created 
Info:        Working on 1772
Info:            Created 
Info:        Working on 1773
Info:            Created 
Info:        Working on 793
Info:            Created 
Info:        Working on 224
Info:            Created 
Info:        Working on 383
Info:            Created 
Info:        Working on 616
Info:            Created 
Info:        Working on 1426
Info:            Created 
Info:        Working on 887
Info:            Created 
Info:        Working on 1178
Info:            Created 
Info:        Working on 1801
Info:            Created 
Info:        Working on 1754
Info:            Created 
Info:        Working on 1829
Info:            Created 
Info:        Working on 1798
Info:            Created 
Info:        Working on 1430
Info:            Created 
Info:        Working on 1544
Info:            Created 
Info:        Working on 1613
Info:            Created 
Info:        Working on 1062
Info:            Created 
Info:        Working on 776
Info:            Created 
Info:        Working on 1337
Info:            Created 
Info:        Working on 1808
Info:            Created 
Info:        Working on 1803
Info:            Created 
Info:        Working on 1670
Info:            Created 
Info:        Working on 1669
Info:            Created 
Info:        Working on 1553
Info:            Created 
Info:        Working on 1749
Info:            Created 
Info:        Working on 1750
Info:            Created 
Info:        Working on 1539
Info:            Created 
Info:        Working on 1538
Info:            Created 
Info:        Working on 1673
Info:            Created 
Info:        Working on 1488
Info:            Created 
Info:        Working on 1347
Info:            Created 
Info:        Working on 1346
Info:            Created 
Info:        Working on 1560
Info:            Created 
Info:        Working on 1650
Info:            Created 
Info:        Working on 1690
Info:            Created 
Info:        Working on 818
Info:            Created 
Info:        Working on 1099
Info:            Created 
Info:        Working on 1097
Info:            Created 
Info:        Working on 782
Info:            Created 
Info:        Working on 1065
Info:            Created 
Info:        Working on 521
Info:            Created 
Info:        Working on 1293
Info:            Created 
Info:        Working on 788
Info:            Created 
Info:        Working on 1076
Info:            Created 
Info:        Working on 1200
Info:            Created 
Info:        Working on 1357
Info:            Created 
Info:        Working on 1498
Info:            Created 
Info:        Working on 1165
Info:            Created 
Info:        Working on 1418
Info:            Created 
Info:        Working on 1842
Info:            Created 
Info:        Working on 1610
Info:            Created 
Info:        Working on 1719
Info:            Created 
Info:        Working on 1855
Info:            Created 
Info:        Working on 1857
Info:            Created 
Info:        Working on 1783
Info:            Created 
Info:        Working on 1824
Info:            Created 
Info:        Working on 1836
Info:            Created 
Info:        Working on 1846
Info:            Created 
Info:        Working on 1816
Info:            Created 
Info:        Working on 1838
Info:            Created 
Info:        Working on 924
Info:            Created 
Info:        Working on 1092
Info:            Created 
Info:        Working on 1359
Info:            Created 
Info:        Working on 1570
Info:            Created 
Info:        Working on 1303
Info:            Created 
Info:        Working on 1393
Info:            Created 
Info:        Working on 1476
Info:            Created 
Info:        Working on 1556
Info:            Created 
Info:        Working on 1593
Info:            Created 
Info:        Working on 770
Info:            Created 
Info:        Working on 1058
Info:            Created 
Info:        Working on 1333
Info:            Created 
Info:        Working on 1549
Info:            Created 
Info:        Working on 1681
Info:            Created 
Info:        Working on 1757
Info:            Created 
Info:        Working on 1631
Info:            Created 
Info:        Working on 1456
Info:            Created 
Info:        Working on 1219
Info:            Created 
Info:        Working on 944
Info:            Created 
Info:        Working on 1131
Info:            Created 
Info:        Working on 1385
Info:            Created 
Info:        Working on 1586
Info:            Created 
Info:        Working on 1708
Info:            Created 
Info:        Working on 1040
Info:            Created 
Info:        Working on 692
Info:            Created 
Info:        Working on 1030
Info:            Created 
Info:        Working on 743
Info:            Created 
Info:        Working on 963
Info:            Created 
Info:        Working on 1044
Info:            Created 
Info:        Working on 1320
Info:            Created 
Info:        Working on 1524
Info:            Created 
Info:        Working on 1020
Info:            Created 
Info:        Working on 755
Info:            Created 
Info:        Working on 232
Info:            Created 
Info:        Working on 390
Info:            Created 
Info:        Working on 619
Info:            Created 
Info:        Working on 902
Info:            Created 
Info:        Working on 336
Info:            Created 
Info:        Working on 543
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 4.46193e-06
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sat Jan 30 13:38:48 2021
